### PR TITLE
Add onPostResetPasswordHook and onPostEnrollAccountHook

### PR DESCRIPTION
**Pull request by todda00**
Add hooks for post enroll and reset password.

These hooks are helpful in routing the user after enrolling or resetting a password instead of staying at the form.

 Note: Ignore the Enroll account form state commit and revert, this is in a separate PR.

### CODE REVIEW

**Comment by timbrandin** [comment]
Alright, looks good. 

I'm all for this, but couldn't it be that what we actually need is a form-submit that is triggered on any formstate instead of on a specific state? Maybe only supporting passing these formSubmit hooks through props also, sliming down the Accounts.ui.options management a bit..?

**Comment by todda00** [comment]
I think I am a fan of having the hooks present in the Accounts.ui.options since its with other hooks (sign in / out), but if you wanted to slim down the options we could create 1 hook which receives the state so people can route or do whatever logic that might differ per state. I am proposing an API like this:

```
Accounts.ui.config({
  onFormSubmitHook: (state) => {
    if(state === STATES.PASSWORD_CHANGE){
      //Do something
    } else if (state === STATES.ENROLL_ACCOUNT) {
      //Do something else
    }
  }
});
```

**Comment by timbrandin** [comment]
Yeah, actually I think that is what people need, right? To be able to hide a popup or overlay after the form was submitted, with or without success.

Maybe one should also have a hook for when switching states?
Like when one press the reset password or change password button.

We should aim for your suggested solution, it's a great start, we could merge this now and start another issue for that transition for the next major version.

**Comment by todda00** [comment]
I previously overlooked the onSubmitHook option that is already present, but I just tried it out and it doesn't fire when I expect it to. Looking at the current code it looks like it is only firing when errors occure during SIGN_UP. Perhaps the best course of action is to fix this hook so it fires when expected?

**Comment by timbrandin** [comment]
Obviously yeah, I forgot about that one. We should definitely try to fix this one first!

Do you want to have a go at it?

**Comment by todda00** [comment]
Yeah I can fix that one, I will open a different PR and if that works out
we can get rid of this one.

**Comment by timbrandin** [comment]
Perfect!

**Comment by todda00** [comment]
#58 has been opened, closing this one.

**Pull request closed without merging**
