### PR TITLE
Fix issue, when message is object in Accounts.ui.FormMessage

### PR DESCRIPTION
**Pull request by lawrentiy**
I don`t now, what happend and in witch version of meteor. But I`ve had troubles with 
meteor/std:accounts-ui
and
zetoff:accounts-material-ui

It`s fast simple fix, checked on meteor 1.4.1 and 1.4.2

### CODE REVIEW

**Comment by PolGuixe** [comment]
@timbrandin seems a legit fix. If you are happy I'll merge it.

**Comment by timbrandin** [comment]
I'm not sure what's the issue here. It feels strange that the message sometimes is an object and sometimes a string. Could we investigate this further before merging it?

**Comment by PolGuixe** [comment]
@lawrentiy `zetoff:accounts-material-ui v0.0.8` fixes an issue https://github.com/Zetoff/accounts-material-ui/issues/14 we had with `FormMessage`, could you let me know if that fixes your previous issue?

**Comment by timbrandin** [comment]
I'm merging this for the reason that it doesn't affect any current behavior, just adding support for the strange situation when the message is of type object.

**Pull request merged**
