### PR TITLE
Fix for the UI component calling the createContainer and assigning it…

### PR DESCRIPTION
**Pull request by josmo**
From issue https://github.com/studiointeract/accounts-ui/issues/117
Without this I'm running into weird issues where it doesn't ever get the user data in Meteor 1.5/1.6

### CODE REVIEW

**Comment by josmo** [comment]
@timbrandin Let me know if this seems reasonable :)

**Comment by josmo** [comment]
@timbrandin just wanted to check on the status of this since it's braking downstream deps :/ I'm totally willing to makes changes :)

**Comment by mutaphysis** [comment]
I stumbled across the same issue, any news on this @timbrandin ?

**Comment by josmo** [comment]
Quick check-in @timbrandin :)

**Pull request merged**
