### PR TITLE
Removed manual calls to React.PropTypes

### PR DESCRIPTION
**Pull request by jLouzado**
* Got a warning that a manual call to React.Proptypes won't be supported in production for the next major versions.
* I just removed them for these three components and moved them inside the class definition.

Warnings are pasted below:
```
Warning: You are manually calling a React.PropTypes validation function for the `onClick` prop on `Button`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

```
Warning: You are manually calling a React.PropTypes validation function for the `oauthServices` prop on `PasswordOrService`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

```
Warning: You are manually calling a React.PropTypes validation function for the `onChange` prop on `Field`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

### CODE REVIEW

**Comment by jLouzado** [comment]
Also, just wondering, does this issue affect my ability to use this package in production right now?

**Comment by serut** [comment]
You missed that usage: https://github.com/jLouzado/accounts-ui/blob/master/imports/ui/components/Form.jsx#L49
Otherwise +1 for merge

**Comment by jLouzado** [comment]
@serut thanks for pointing it out... made that change as well. :)

**Comment by serut** [comment]
Ok sorry but I misread. Your commit is still not right (on all files) because React.PropTypes is deprecated as of React v15. You need to change everytime you see 
```
onClick: React.PropTypes.func
```
into
```
onClick: PropTypes.func
```

You will need to import PropTypes as following:
```
import PropTypes from 'prop-types'
```

And add the dependency to the package.json
```
npm install --save prop-types
```

**Comment by jLouzado** [comment]
@serut sorry if this sounds noobish but could you just share build instructions for this package please? As in, how are you testing this on your end...

**Comment by jLouzado** [comment]
Anyway, I just made the changes and pushed them.

**Comment by serut** [comment]
No problem ! I was trying to setup tests and coverage on that repository https://github.com/apollographql/meteor-starter-kit.

What you can do to test it:

```
git clone https://github.com/apollographql/meteor-starter-kit
mkdir packages # Create a folder to hold meteor packages
cd packages
git clone https://github.com/jLouzado/accounts-ui # When you clone a package inside that directory, meteor will use your version and not the one from atmosphere
cd ..
meteor
```
Then open the browser and look at the console

**Comment by jLouzado** [comment]
Done done... are those all the changes?

**Comment by serut** [comment]
Yes it ok for me ! Well done

**Comment by purplecones** [comment]
When will this be merged?

**Comment by firrae** [comment]
Any update on this getting pulled in?

**Comment by jLouzado** [comment]
Sweet... thanks guys. :pray:

**Pull request merged**
